# Site settings
title: WQTeam
email: xinwang@woqu.com
url: https://github.com/WQTeam
description: "We are so diao, to be niubility!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: WQTeam
  location: 追踪我们
  social: 加入我们
  slogan: 我们的口号

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/WQTeam

# Postal address (add as many lines as necessary)
address:
  - line: 广东省，深圳市，南山区科技园南四道
  - line: 创维半导体大厦西座四楼我趣旅行

# Slogan content
slogan:
  - line: 'We are so diao, to be niubility!'

# Build settings
markdown: kramdown
permalink: pretty
